### ISSUE TITLE
Create DAO layer interface for MushroomHunter entity

### ISSUE THREAD

**Issue by bkompis** [PA165-MushroomHunter/MushroomHunter#12]

**Comment by bkompis** [comment]
Research possible use of org.springframework.data.jpa.repository.JpaRepository (should generate the JPA implementation of the DAO classes (see milestone requirements)).

**Comment by bkompis** [comment]
Still missing the ``update`` method and validity checks in implementations.

**Comment by Buvko** [comment]
Hmm, there is update method and there are null checks, could you specify the place where they are missing?

**Comment by bkompis** [comment]
Created in #26, finalized in #48.
