### ISSUE TITLE
Create DAO layer interface for Forest entity

### ISSUE THREAD

**Issue by bkompis** [PA165-MushroomHunter/MushroomHunter#13]

**Comment by bkompis** [comment]
Research possible use of org.springframework.data.jpa.repository.JpaRepository (should generate the JPA implementation of the DAO classes (see milestone requirements)).

**Comment by bencikpeter** [comment]
@bkompis I believe that just using Hibernate to perform CRUD ops is enough to satisfy "JPA implementation of DAO classes". But I will look at it anyway...

**Comment by bkompis** [comment]
Still missing the ``update`` method and validity checks in implementations.

**Comment by bkompis** [comment]
Finalized in #38 and #48.
