### ISSUE TITLE
Implement controller and viewer for registering new Mushroom Hunters(Users)

### ISSUE THREAD

**Issue by Buvko** [PA165-MushroomHunter/MushroomHunter#138]
Implement controller and viewer for registering new Mushroom Hunters(Users)
- This page should be only accessible by user with ADMIN rights!
- On this page I suggest there can be table of Mushroom Hunters
- The table should have all the attributes of Mushroom Hunters
- On this page there will be an ability to edit Mushroom Hunters and approve the new ones

There is nothing said about responsivnes in milestone, but perphaps we could implement it also.
Interfere only with facade/REST layer not service or DB layer.

**Comment by bkompis** [comment]
In #141:
* Registering is open to anyone (a non-logged in user can register), no way of approving registrations is implemented. 
* List of users is visible and accessible only to admins. They can update and delete any user.
* A non-administrator user can only acces his/her own profile, and can edit and delete it.
* Pages use the facade layer of the application.
