### ISSUE TITLE
Prepare controller and viewer for Index page

### ISSUE THREAD

**Issue by Buvko** [PA165-MushroomHunter/MushroomHunter#139]
Prepare Index page controller and viewer
- On this page there should be a form for logging the user in.
    - After successful login user will be redirected to Mushroom page
    - After unsuccessful login user will be told that used credentials are incorrect
- On this page there should be and "Register as a new Mushroom Hunter"
    - Click on this page should lead to form for registering new Mushroom Hunter
- Prepare Log out controller ad listerner for "Log Out button" which logs user out and redirects him to this page

**Comment by bkompis** [comment]
In #141. 
Just a basic page. All functionality (login/register, accessing entity lists, home button) is stored in a toolbar at the top of the page.

The page could use some updates later, so it isn't so empty, Or we could change the page layout,
