### ISSUE TITLE
Prepare REST interface for chosen entity

### ISSUE THREAD

**Issue by Buvko** [PA165-MushroomHunter/MushroomHunter#140]
Prepare REST interface for chosen entity and expose one operation for it.
For example: 
- Registering new Forest via GET or POST
- Getting information about some Mushroom via GET by its name in URL

**Comment by bkompis** [comment]
In #141, a REST interface is done for the MushroomHunter entity. Supported functions:
* get by id
* find all
* create
* update
* delete
