### ISSUE TITLE
Presentation + Brief documentation of the app

### ISSUE THREAD

**Issue by bohdancvejn** [PA165-MushroomHunter/MushroomHunter#161]
[Mushroom_Hunter_presentation.pptx](https://github.com/PA165-MushroomHunter/MushroomHunter/files/1609897/Mushroom_Hunter_presentation.pptx)

**Comment by bohdancvejn** [comment]
@All: please add in the presentation your points - like what did you like, dislike, etc.

If you want to change some slide, please feel free to do it :)

**Comment by bohdancvejn** [comment]
Last version (updates from Lida included)
[Mushroom Hunter manual-draft.docx](https://github.com/PA165-MushroomHunter/MushroomHunter/files/1610745/Mushroom.Hunter.manual-draft.docx)

**Comment by bkompis** [comment]
How about an online editable format for the presentation? Like this here:
https://docs.google.com/presentation/d/1tRtm_lmP7ZwtKCzwA12bbxT6GV-_YQj6N5iMYn8MN0I/edit?usp=sharing
I've copied the content of the presentation linked here, and edited some things.
