### ISSUE TITLE
[Discussion] Add relationships containing the Mushroom entity

### ISSUE THREAD

**Issue by bkompis** [PA165-MushroomHunter/MushroomHunter#60]
But first, a discussion is in order: do we need / want to add the relationsthips?

My proposal for entity relationships is:

MushroomHunter -- OneToMany -- Visit - ManyToOne -- Forest
Mushroom -- ManyToMany -- Visit
*Maybe:* Forest -- ManyToMany -- Mushroom

**Comment by Buvko** [comment]
I would prefer Mushroom <-> Visist relationship, because the hunter should easily submit new visit as set of Forest + Mushroom(0 .. N) + (implicitly him)

**Comment by bohdancvejn** [comment]
I'm still not sure if we have to add "Mushroom" entity to anything. I would make just a catalogue of mushrooms and that's all.

I like more "Mushroom -- ManyToMany -- Visit" relation than "Forest -- ManyToMany -- Mushroom" so I would like to go "M<>V" way.

@Buvko : Visit should be a "Visit(hunter, forest)" and it is not clear to me, how you wanna build a set of mushroom in it :)

**Comment by bencikpeter** [comment]
I agree with @bohdancvejn on this one. I believe we are just creating unnecessary work for ourselves. I would just have catalogue as a separate module and have it just as a separate page (or whatever GUI element we will be using) with the catalogue functionality

**Comment by bkompis** [comment]
**Final decision: we add a relationship Visit -- OneToMany -- Mushroom to use in the service layer.**
